gym_app/urls.py
from django.contrib import admin
from django.urls import path
from gym_app import views, adminviews, instructorviews,physicianviews,userviews

urlpatterns = [

    path('',views.index, name='index'),
    path('about/',views.about, name='about'),
    path('index/',views.batches, name='batches'),
    path('instructor/',views.instructor, name='instructor'),
    path('contact/',views.contact, name='contact'),
    path('batches/',views.batches, name='batches'),
    path('service/',views.service, name='service'),
    path('gallery/',views.gallery, name='gallery'),
    path('login_view/',views.login_view, name='login_view'),
    path('admin_page/', views.admin_page, name='admin_page'),
    path('instructor_register/', views.instructor_register, name='instructor_register'),
    path('physician_register/', views.physician_register, name='physician_register'),
    path('customer_register/', views.customer_register, name='customer_register'),
    path('view_staff/', adminviews.staff_view, name='view_staff'),
    path('delete_staff/<int:id>/', adminviews.delete_staff, name='delete_staff'),
    path('logout_view/', views.logout_view, name='logout_view'),

    path('view_user/', adminviews.user_view, name='view_user'),
    path('approve_user/<str:user_id>/', adminviews.approve_user, name='approve_user'),
    path('add_batch/', adminviews.add_batch, name='add_batch'),
    path('add_instructor/', adminviews.add_instructor, name='add_instructor'),
    path('view_attendance_admin/', adminviews.view_attendance_admin, name='view_attendance_admin'),
    path('add_bill/', adminviews.bill, name='add_bill'),
    path('view_bill/', adminviews.view_bill, name='view_bill'),
    path('add_service/', adminviews.add_service, name='add_service'),
    path('view_service/', adminviews.view_service, name='view_service'),
    path('edit_service/<int:id>/', adminviews.edit_service, name='edit_service'),
    path('delete_service/<int:id>/', adminviews.delete_service, name='delete_service'),
    path('view_complaint/', adminviews.view_complaint, name='view_complaint'),
    path('reply_complaint/<int:id>/', adminviews.reply_complaint, name='reply_complaint'),
    path('delete_complaint/<int:id>/', adminviews.delete_complaint, name='delete_complaint'),
    path('add_equipment/', adminviews.add_equipment, name='add_equipment'),
    path('view_equipment/', adminviews.view_equipment, name='view_equipment'),
    path('edit_equipment/<int:id>/', adminviews.edit_equipment, name='edit_equipment'),
    path('delete_equipment/<int:id>/', adminviews.delete_equipment, name='delete_equipment'),
    path('day_attendance_admin/<date>/', adminviews.day_attendance_admin, name='day_attendance_admin'),
    path('ajax/load-batch/', views.load_batch, name='ajax_load_batch'),  # AJAX
    path('ajax/load-bill/', adminviews.load_bill, name='ajax_load_bill'),  # AJAX
    path('view_batches/', adminviews.view_batches, name='view_batches'),  # AJAX

    path('instructor_page/', views.instructor_page, name='instructor_page'),
    path('add_health/', instructorviews.add_health, name='add_health'),
    path('view_health/', instructorviews.view_health_issue, name='view_health'),
    path('edit_health/<int:id>/', instructorviews.edit_health_issue, name='edit_health_issue'),
    path('add_diet/', instructorviews.add_diet, name='add_diet'),
    path('view_diet/', instructorviews.view_diet, name='view_diet'),
    path('edit_diet/<int:id>/', instructorviews.edit_diet, name='edit_diet'),
    path('delete_diet/<int:id>/', instructorviews.delete_diet, name='delete_diet'),
    path('add_attendance/', instructorviews.add_attendance, name='add_attendance'),
    path('view_attendance/', instructorviews.view_attendance, name='view_attendance'),
    path('view_firstaid_instructor/', instructorviews.view_firstaid_instructor, name='view_firstaid_instructor'),
    path('mark/<int:id>/', instructorviews.mark, name='mark'),
    path('day_attendance/<date>/', instructorviews.day_attendance, name='day_attendance'),




    path('physician_page/', views.physician_page, name='physician_page'),
    path('view_user_health/', physicianviews.view_user_health, name='view_user_health'),
    path('edit_user_health/<int:id>/', physicianviews.edit_user_health, name='edit_user_health'),
    path('view_appointment/', physicianviews.view_appointment, name='view_appointment'),
    path('approve_appointment/<int:id>/', physicianviews.approve_appointment, name='approve_appointment'),
    path('reject_appointment/<int:id>/', physicianviews.reject_appointment, name='reject_appointment'),
    path('add_first_aid/', physicianviews.add_first_aid, name='add_first_aid'),
    path('view_first_aid/', physicianviews.view_first_aid, name='view_first_aid'),
    path('edit_first_aid/<int:id>/', physicianviews.edit_first_aid, name='edit_first_aid'),
    path('delete_first_aid/<int:id>/', physicianviews.delete_first_aid, name='delete_first_aid'),
    path('view_medicaldoubts_physician/', physicianviews.view_medicaldoubts_physician, name='view_medicaldoubts_physician'),
    path('reply_doubt/<int:id>/', physicianviews.reply_doubts, name='reply_doubts'),
    path('consultation_time/', physicianviews.consultation_time, name='consultation_time'),


    path('user_page/', views.user_page, name='user_page'),
    path('view_batch_user/',userviews.view_batch_user, name='view_batch_user'),
    path('view_diet_user/',userviews.view_diet_user, name='view_diet_user'),
    path('take_appointment/',userviews.take_appointment, name='take_appointment'),
    path('view_appointment_user/',userviews.view_appointment_user, name='view_appointment_user'),
    path('view_equipment_user/', userviews.view_equipment_user, name='view_equipment_user'),
    path('ask_doubts/', userviews.ask_doubts, name='ask_doubts'),
    path('view_doubt/', userviews.view_doubt, name='view_doubt'),
    path('edit_doubt/<int:id>/', userviews.edit_doubt, name='edit_doubt'),
    path('delete_doubt/<int:id>/', userviews.delete_doubt, name='delete_doubt'),
    path('add_complaint/', userviews.add_complaint, name='add_complaint'),
    path('view_complaint_user/', userviews.view_complaint_user, name='view_complaint_user'),
    path('view_attendance_user/', userviews.view_attendance_user, name='view_attendance_user'),
    path('get_invoice/<int:id>/', userviews.get_invoice, name='get_invoice'),
    path('view_invoice/<int:id>/', userviews.view_invoice, name='view_invoice'),

    path('view_bill_user/', userviews.view_bill_user, name='view_bill_user'),
    path('pay_bill/<int:id>/', userviews.pay_bill, name='pay_bill'),
    path('bill_history/', userviews.bill_history, name='bill_history'),
    path('view_transformation/', userviews.view_transformation, name='view_transformation'),
    path('bmi/', userviews.bmi, name='bmi'),
    path('view_bmi/<bmi>/', userviews.view_bmi, name='view_bmi'),
    path('drop_gym/', userviews.drop_gym, name='drop_gym'),
    path('pay_in_direct/<int:id>/', userviews.pay_in_direct, name='pay_in_direct'),

]

smart_gym/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from smart_gym import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gym_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym_app/forms.py
import datetime
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.forms import PasswordInput, SplitDateTimeWidget
from gym_app.models import User, Register, Batch, Instructor, Bill, Services, Equipment, DietPlan, FirstAid, \
    Appointment, Doubts, Complaints, CreditCard, UserHealth
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker


class AddBatch(forms.ModelForm):
    batch_time = forms.TimeField(
        widget=TimePicker(
            options={
                'format': 'hh:mm A'
            },
            attrs={
                'append': 'fa fa-clock-o',
                'icon_toggle': True,
            },
        ),
    )

    class Meta:
        model = Batch
        fields = ('batch_name', 'batch_time')


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.TimeInput):
    input_type = 'time'


def phone_number_validator(value):
    if not re.compile(r'^[7-9]\d{9}$').match(value):
        raise ValidationError('This is Not a Valid Phone Number')


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class LoginRegister(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput, )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


gender_choice = (
    ("Male", "Male"),
    ("Female", "Female")
)


class PhysicianSignUpForm(forms.ModelForm):
    consultation_time = forms.TimeField(
        widget=TimePicker(
            options={
                'format': 'hh:mm A'
            },
            attrs={
                'append': 'fa fa-clock-o',
                'icon_toggle': True,
            },
        ),
    )
    phone_no = forms.CharField(validators=[phone_number_validator])
    gender = forms.ChoiceField(choices=gender_choice, required=True, widget=forms.RadioSelect)

    date_of_birth = forms.DateField(widget=DateInput)
    email = forms.CharField(validators=[
        RegexValidator(regex='^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', message='Please Enter a Valid Email')])

    class Meta:
        model = Register
        fields = ('name', 'date_of_birth', 'gender', 'phone_no', 'email', 'address', 'qualification',
                  'consultation_time', 'photo')
        widgets = {
            'photo': forms.FileInput(attrs={'class': 'form-control'}),

        }

    def clean_date_of_birth(self):
        date = self.cleaned_data['date_of_birth']

        if date >= datetime.date.today():
            raise forms.ValidationError("Invalid Date")
        return date

    def clean_email(self):
        mail = self.cleaned_data['email']
        mail_qs = Register.objects.filter(email=mail)
        if mail_qs.exists():
            raise forms.ValidationError("This email  already registered")
        return mail

    def clean_phone_no(self):
        phone = self.cleaned_data['phone_no']
        phone_qs = Register.objects.filter(phone_no=phone)
        if phone_qs.exists():
            raise forms.ValidationError("This Phone Number already registered")
        return phone


class InstructorSignUpForm(forms.ModelForm):
    phone_no = forms.CharField(validators=[phone_number_validator])
    gender = forms.ChoiceField(choices=gender_choice, required=True, widget=forms.RadioSelect)
    date_of_birth = forms.DateField(widget=DateInput)
    email = forms.CharField(validators=[
        RegexValidator(regex='^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', message='Please Enter a Valid Email')])

    class Meta:
        model = Register
        fields = ('name', 'date_of_birth', 'gender', 'phone_no', 'email', 'address', 'qualification', 'photo')
        widgets = {
            'photo': forms.FileInput(attrs={'class': 'form-control'})
        }

    def clean_date_of_birth(self):
        date = self.cleaned_data['date_of_birth']

        if date >= datetime.date.today():
            raise forms.ValidationError("Invalid Date")
        return date

    def clean_email(self):
        mail = self.cleaned_data['email']
        mail_qs = Register.objects.filter(email=mail)
        if mail_qs.exists():
            raise forms.ValidationError("This email  already registered")
        return mail

    def clean_phone_no(self):
        phone = self.cleaned_data['phone_no']
        phone_qs = Register.objects.filter(phone_no=phone)
        if phone_qs.exists():
            raise forms.ValidationError("This Phone Number already registered")
        return phone


class CustomerSignUpForm(forms.ModelForm):
    phone_no = forms.CharField(validators=[phone_number_validator])
    gender = forms.ChoiceField(choices=gender_choice, required=True, widget=forms.RadioSelect)
    date_of_birth = forms.DateField(widget=DateInput)
    email = forms.CharField(validators=[
        RegexValidator(regex='^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', message='Please Enter a Valid Email')])

    class Meta:
        model = Register
        fields = (
            'name', 'date_of_birth', 'gender', 'phone_no', 'email', 'address', 'occupation', 'required_batch_name',
            'required_batch_time', 'photo')
        widgets = {
            'photo': forms.FileInput(attrs={'class': 'form-control'})
        }

    def clean_date_of_birth(self):
        date = self.cleaned_data['date_of_birth']

        if date >= datetime.date.today():
            raise forms.ValidationError("Invalid Date")
        return date

    def clean_email(self):
        mail = self.cleaned_data['email']
        mail_qs = Register.objects.filter(email=mail)
        if mail_qs.exists():
            raise forms.ValidationError("This email  already registered")
        return mail

    def clean_phone_no(self):
        phone = self.cleaned_data['phone_no']
        phone_qs = Register.objects.filter(phone_no=phone)
        if phone_qs.exists():
            raise forms.ValidationError("This Phone Number already registered")
        return phone


class AddInstructor(forms.ModelForm):
    instructor = forms.ModelChoiceField(queryset=Register.objects.filter(role='Instructor'))

    class Meta:
        model = Instructor
        fields = '__all__'


class AddBill(forms.ModelForm):
    name = forms.ModelChoiceField(queryset=Register.objects.filter(role='Customer'))
    from_date = forms.DateField(widget=DateInput)
    to_date = forms.DateField(widget=DateInput)
    due_date = forms.DateField(widget=DateInput)

    class Meta:
        model = Bill
        exclude = ('status', 'paid_on')

    def clean(self):
        cleaned_data = super().clean()
        from_date = cleaned_data.get("from_date")
        to_date = cleaned_data.get("to_date")
        due_date = cleaned_data.get("due_date")

        if (from_date > datetime.date.today()):
            raise forms.ValidationError("Invalid From Date")
        if to_date <= from_date:
            raise forms.ValidationError("Invalid To Date")
        if due_date < datetime.date.today():
            raise forms.ValidationError("Invalid Due Date")
        return cleaned_data


class AddService(forms.ModelForm):
    class Meta:
        model = Services
        fields = '__all__'


class AddEquipment(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = '__all__'


class AddDietPlan(forms.ModelForm):
    class Meta:
        model = DietPlan
        fields = '__all__'


class FirstAidForm(forms.ModelForm):
    class Meta:
        model = FirstAid
        fields = '__all__'


class AppointmentForm(forms.ModelForm):
    physician = forms.ModelChoiceField(queryset=Register.objects.filter(role='Physician'))
    date = forms.DateField(widget=DateInput)

    class Meta:
        model = Appointment
        fields = ('physician', 'date')

    def clean_date(self):
        date = self.cleaned_data['date']
        if date < datetime.date.today():
            raise forms.ValidationError("Invalid Date")
        return date


class AskDoubtForm(forms.ModelForm):
    physician = forms.ModelChoiceField(queryset=Register.objects.filter(role='Physician'))

    class Meta:
        model = Doubts
        fields = ('physician', 'doubts')


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaints
        fields = ('complaint',)


class PayBillForm(forms.ModelForm):
    card_no = forms.CharField(validators=[RegexValidator(regex='^.{16}$', message='Please Enter a Valid Card No')])
    card_cvv = forms.CharField(widget=forms.PasswordInput,
                               validators=[RegexValidator(regex='^.{3}$', message='Please Enter a Valid CVV')])
    expiry_date = forms.DateField(widget=DateInput(attrs={'id': 'example-month-input'}))

    class Meta:
        model = CreditCard
        fields = ('card_no', 'card_cvv', 'expiry_date')

    def clean(self):
        cleaned_data = super().clean()
        expiry_date = cleaned_data.get("expiry_date")

        if (expiry_date < datetime.date.today()):
            raise forms.ValidationError("This card has Expired")

        return cleaned_data


class UserHealthForm(forms.ModelForm):
    name = forms.ModelChoiceField(queryset=Register.objects.filter(role='Customer'))

    class Meta:
        model = UserHealth
        exclude = ('instructor', 'transformation_status')


class UserHealthUpdateForm(forms.ModelForm):
    name = forms.ModelChoiceField(queryset=Register.objects.filter(role='Customer'))

    class Meta:
        model = UserHealth
        fields = ('name', 'height', 'weight', 'health_issue', 'medicine_consumption')

    def __init__(self, *args, **kwargs):
        super(UserHealthUpdateForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)

templates/admintemp/add_instructor.html
{% extends 'admintemp/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="col-lg-8 col-ml-8">
    <div class="row">

        <!-- basic form start -->
        <div class="col-12 mt-5">
            <div class="card">
                {% for message in messages %}
                <div class="alert alert-info" role="alert">
                    <strong>{{message}}</strong>
                </div>
                {% endfor %}
                <div class="card-body">
                    <h4 class="header-title">Add Instructor</h4>
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                        {{form|crispy}}

                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                    </form>


                </div>
            </div>
        </div>
        <!-- basic form end -->

    </div>
</div>
{% endblock %}

templates/admintemp/customer_register.html
{% extends 'admintemp/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="col-lg-8 col-ml-8">
    <div class="row">

        <!-- basic form start -->
        <div class="col-12 mt-5">
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
                <strong>{{message}}</strong>
            </div>
            {% endfor %}
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Register Customer</h4>
                    <form method="post" enctype="multipart/form-data" id="form" data-batch-url="{% url 'ajax_load_batch' %}">{% csrf_token %}
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {{ customer_form.name|as_crispy_field }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6">
                                {{customer_form.date_of_birth|as_crispy_field}}

                            </div>

                            <div class="col-sm-6">
                                <div class="custom-control custom-radio custom-control-inline">
                                    {{customer_form.gender|as_crispy_field}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{customer_form.address|as_crispy_field}}
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-4">
                                {{customer_form.email|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{customer_form.phone_no|as_crispy_field}}
                            </div>
                            <div class="col-sm-4">
                                {{customer_form.occupation|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                {{customer_form.photo|as_crispy_field}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6">
                                {{customer_form.required_batch_name|as_crispy_field}}
                            </div>
                            <div class="col-sm-6">
                                {{customer_form.required_batch_time|as_crispy_field}}
                            </div>
                        </div>
                        {{login_form|crispy}}


                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                    </form>


                </div>
            </div>
        </div>
        <!-- basic form end -->

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_required_batch_name").change(function () {
        const url = $("#form").attr("data-batch-url");  // get the url of the `load_cities` view
        const batchId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'batch_id': batchId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $( "#id_required_batch_time" ).val(data.required_batch_time);
           console.log('The value captured is: ' + data.required_batch_time)
                }

        });

    });
</script>
{% endblock %}

templates/admintemp/day_attendance.html
{% extends 'admintemp/base.html' %}
{% block content %}


<div class="col-lg-12 mt-5">

    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        <strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">

        <div class="card-body">
            <h4 class="header-title"> Attendance on {{date}}</h4>

            <div class="single-table">
                <div class="table-responsive">
                    <table class="table text-center">
                        <thead class="text-uppercase bg-secondary">
                        <tr class="text-white">
                            <th>SINo</th>
                            <th>Name</th>
                            <th>Attendance</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for attendance in attendances %}
                        <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{attendance.name}}</td>
                            <td>{{attendance.attendance}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
window.mytest = function()
{ var isValid = confirm('Are you sure Want to Delete ?');if (!isValid) { event.preventDefault();
  }}



</script>
{% endblock %}

templates/admintemp/delete_equipment.html
{% extends 'admintemp/base.html' %}
{% block content %}
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Delete Equipment</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <form method="post">{% csrf_token %}
                        <div class="card-body">

                            <h1> Are You Sure Want to Delete?</h1>
                            <br>
                            <br>
                            <br>


                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">YES</button>
                                <a href="{% url 'view_equipment' %}" type="submit" class="btn btn-primary ">CANCEL</a>
                            </div>
                        </div>

                    </form>

                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->


        </div>
    </div>
</section>
<!-- /.content -->
{% endblock %}

templates/admintemp/delete_staff.html
{% extends 'admintemp/base.html' %}
{% block content %}
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Delete Staff</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <form method="post">{% csrf_token %}
                        <div class="card-body">

                            <h1> Are You Sure Want to Delete?</h1>
                            <br>
                            <br>
                            <br>

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">YES</button>
                                <a href="{% url 'view_staff' %}" type="submit" class="btn btn-primary ">CANCEL</a>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</section>
<!-- /.content -->
{% endblock %}

templates/admintemp/generate_bill.html
{% extends 'admintemp/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="col-lg-8 col-ml-8">
    <div class="row">
        <!-- basic form start -->
        <div class="col-12 mt-5">
             {% for message in messages %}
        <div class="alert alert-info" role="alert">
            <strong>{{message}}</strong>
        </div>
        {% endfor %}
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Add Bill</h4>
                    <form method="post" id="form" data-bill-url="{% url 'ajax_load_bill' %}">{% csrf_token %}
                        {{form|crispy}}

                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                    </form>


                </div>
            </div>
        </div>
        <!-- basic form end -->

    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_to_date").change(function () {
        const url = $("#form").attr("data-bill-url");

        const to_date = $(this).val();
       const from_date = document.getElementById("id_from_date").value;
       const customerId = document.getElementById("id_name").value;



        $.ajax({
            url: url,
            data: {
                'to_date': to_date,
                'from_date': from_date,
                'customerId': customerId,

            },
            success: function (data) {
                $( "#id_present_days" ).val(data.present_days);
                $( "#id_amount" ).val(data.amount);

                }

        });

    });


</script>
{% endblock %}

templates/admintemp/reply_complaint.html
{% extends 'admintemp/base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div class="col-lg-8 col-ml-8">
    <div class="row">
        <!-- basic form start -->
        <div class="col-12 mt-5">
               {% for message in messages %}
                    <div class="alert alert-info" role="alert">
                        <strong>{{message}}</strong>
                    </div>
                    {% endfor %}
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Reply Complaint</h4>
                    <form method="post" enctype="multipart/form-data">{% csrf_token %}
                         <div class="form-group">
                           {{form|crispy}}
                        </div>
                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Submit</button>
                    </form>


                </div>
            </div>
        </div>
        <!-- basic form end -->

    </div>
</div>
{% endblock %}

templates/admintemp/view_attendance_admin.html
{% extends 'admintemp/base.html' %}
{% block content %}


<div class="col-lg-12 mt-5">

    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
        <strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div class="card">

        <div class="card-body">
            <h4 class="header-title">User Attendance</h4>

            <div class="single-table">
                <div class="table-responsive">
                    <table class="table text-center">
                        <thead class="text-uppercase bg-secondary">
                        <tr class="text-white">

                            <th>SINo</th>
                            <th>Name</th>
                            <th>View</th>

                        </tr>
                        </thead>
                        <tbody>

                        {% for attendance in attendances %}
                        <tr>
                            <td>{{forloop.counter }}</td>
                            <td>{{ attendance}}</td>
                            <td><a href="{% url 'day_attendance_admin' attendance %}">View</a></td>

                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}